# Use the official Alpine Linux image as the base image
FROM alpine:latest

# Set the working directory (optional)
WORKDIR /app

# Specify the command to run the application
CMD ["echo", "This output has been provided by the m3c5s-tools-test Docker image."]
